# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            "Sandor Nemeth's blog"
tagline:          'Developer weblog'
description:      "A developer's weblog"
baseurl:          /

author:
  name:           'Sandor Nemeth'
  url:            https://twitter.com/sandor_nemeth

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/sandor-nemeth/sandor-nemeth.github.io
