# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: devlog
email: sandor.nemeth.1986@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Java developer, interested in the cloud
    Everything here is to be treated as an opinion. The posts posted here
    represent my opinions and mine only. They do not represent any organization I am (or was) associated.
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /article/:categories/:year/:month/:day/:title
facebook_username: sandor.nemeth.1986
twitter_username: sandor_nemeth
github_username:  sandor-nemeth
generator:  Sandor Nemeth

# Build settings
markdown: kramdown

# Plugins
gems:
  - jemoji
  - jekyll-sitemap
