title: devlog
description: >
  This is the place where I dump my thoughts. All things published here are mine, 
  and do not represent any organizations I am/was associated with. 
email: sandor.nemeth.1986@gmail.com
twitter_username: sandor_nemeth
github_username:  sandor-nemeth
repository: sandor-nemeth/sandor-nemeth.github.io
avatar_url: /assets/images/avatar.jpg

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  sass_dir: _sass
  # style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
