title: devlog
email: sandor.nemeth.1986@gmail.com
twitter_username: sandor_nemeth
github_username:  sandor-nemeth
repository: sandor-nemeth/sandor-nemeth.github.io

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  sass_dir: _sass
  # style: compressed

gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
